### ISSUE TITLE
build.sh Run on linux(debian) failed

### ISSUE THREAD

**Issue by zaaack** [SAFE-Stack/SAFE-BookStore#217]
When I run `build.sh Run` in linux debian, got an error:

```sh

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/navigation.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/navigation.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 18:0-174
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 16:0-148
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish.debugger/1.0.0/fable/debugger.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish.debugger/1.0.0/fable/debugger.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 25:0-125
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish.hmr/1.0.0/fable/hmr.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish.hmr/1.0.0/fable/hmr.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 27:0-134
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 26:0-121
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish/1.0.0/fable/cmd.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish/1.0.0/fable/cmd.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 17:0-107
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.elmish/1.0.0/fable/program.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.elmish/1.0.0/fable/program.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./App.fs 24:0-143
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Fetch.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Fetch.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./pages/WishList.fs 11:0-136
 @ ./App.fs
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Promise.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Promise.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./pages/WishList.fs 12:0-129
 @ ./App.fs
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj

ERROR in /media/z/data/home/z/.nuget/packages/fable.react/1.2.1/fable/Fable.Helpers.React.fs
Module build failed: Error: /media/z/data/home/z/.nuget/packages/fable.react/1.2.1/fable/Fable.Helpers.React.fs doesn't belong to any of loaded projects [[/media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj, /media/z/data/home/z/Projects/Strawberry/backend/src/Client/Client.fsproj]]
    at Loader.fableUtils.client.send.then.r (/media/z/data/home/z/Projects/Strawberry/backend/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ./Style.fs 5:0-124
 @ ./App.fs
 @ ./Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./Client.fsproj
```

**Comment by MangelMaxime** [comment]
I am under Kubuntu 17.04 and with a fresh clone and this is working. @zaaack Are you using a fresh clone project ? If not can you please try.

@alfonsogarciacaro I remember that some people was having this errors like 1-2 weeks ago but never manage to find the root of it.

**Comment by zaaack** [comment]
@MangelMaxime Yeah, I tried  fresh clone, and still got this  error. But if I build the fable template project following the fable tutorial, it is working.

**Comment by zaaack** [comment]
@MangelMaxime Yeah, I tried  fresh clone, and still got this  error. But if I build the fable template project following the fable tutorial, it is working.

**Comment by zaaack** [comment]
@MangelMaxime I think I find out why...

Here is the log of run `dotnet fable` in verbose mode:
```sh
F# PROJECT: ./Client.fsproj
   --noframework
   --nologo
   --simpleresolution
   --nocopyfsharpcore
   --define:FABLE_COMPILER
   --define:DEBUG
   --optimize-
   --warn:3
   --fullpaths
   --flaterrors
   --target:library
   --targetprofile:netcore
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.XPath.XDocument.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.XPath.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.XmlSerializer.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.XmlDocument.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.XDocument.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.Serialization.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.ReaderWriter.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.Linq.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Xml.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Windows.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Web.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ValueTuple.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Transactions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.Timer.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.ThreadPool.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.Thread.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.Tasks.Parallel.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.Tasks.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.Overlapped.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Threading.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Text.RegularExpressions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Text.Encoding.Extensions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Text.Encoding.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ServiceModel.Web.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.SecureString.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Principal.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Cryptography.X509Certificates.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Cryptography.Primitives.dll
   -r:/home/z/.nuget/packages/system.security.cryptography.openssl/4.4.0/ref/netstandard2.0/System.Security.Cryptography.OpenSsl.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Cryptography.Encoding.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Cryptography.Csp.dll
   -r:/home/z/.nuget/packages/system.security.cryptography.cng/4.4.0/ref/netstandard2.0/System.Security.Cryptography.Cng.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Cryptography.Algorithms.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Security.Claims.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Serialization.Xml.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Serialization.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Serialization.Json.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Serialization.Formatters.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Serialization.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Numerics.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.InteropServices.RuntimeInformation.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.InteropServices.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Handles.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.Extensions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Runtime.CompilerServices.VisualC.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Resources.Writer.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Resources.ResourceManager.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Resources.Reader.dll
   -r:/home/z/.nuget/packages/system.reflection.typeextensions/4.4.0/ref/netstandard2.0/System.Reflection.TypeExtensions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Reflection.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Reflection.Extensions.dll
   -r:/home/z/.nuget/packages/system.reflection.emit.lightweight/4.3.0/ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll
   -r:/home/z/.nuget/packages/system.reflection.emit.ilgeneration/4.3.0/ref/netstandard1.0/System.Reflection.Emit.ILGeneration.dll
   -r:/home/z/.nuget/packages/system.reflection.emit/4.3.0/ref/netstandard1.1/System.Reflection.Emit.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Reflection.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ObjectModel.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Numerics.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.WebSockets.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.WebSockets.Client.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.WebHeaderCollection.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Sockets.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Security.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Requests.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Ping.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.NetworkInformation.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.NameResolution.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.Http.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Net.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Linq.Queryable.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Linq.Parallel.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Linq.Expressions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Linq.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.UnmanagedMemoryStream.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.Pipes.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.MemoryMappedFiles.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.IsolatedStorage.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.FileSystem.Watcher.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.FileSystem.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.FileSystem.DriveInfo.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.FileSystem.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.Compression.ZipFile.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.Compression.FileSystem.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.IO.Compression.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Globalization.Extensions.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Globalization.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Globalization.Calendars.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Dynamic.Runtime.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Drawing.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Drawing.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.Tracing.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.TraceSource.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.Tools.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.TextWriterTraceListener.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.StackTrace.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.Process.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.FileVersionInfo.dll
   -r:/home/z/.nuget/packages/system.diagnostics.diagnosticsource/4.4.1/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.Debug.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Diagnostics.Contracts.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Data.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Data.Common.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Core.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Console.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ComponentModel.TypeConverter.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ComponentModel.Primitives.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ComponentModel.EventBasedAsync.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ComponentModel.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.ComponentModel.Composition.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Collections.Specialized.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Collections.NonGeneric.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Collections.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.Collections.Concurrent.dll
   -r:/home/z/.nuget/packages/system.buffers/4.4.0/ref/netstandard2.0/System.Buffers.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/System.AppContext.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/netstandard.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/mscorlib.dll
   -r:/home/z/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref/Microsoft.Win32.Primitives.dll
   -r:/home/z/.nuget/packages/fsharp.core/4.2.3/lib/netstandard1.6/FSharp.Core.dll
   -r:/home/z/.nuget/packages/fable.import.browser/0.1.0/lib/netstandard1.6/Fable.Import.Browser.dll
   -r:/home/z/.nuget/packages/fable.core/1.2.4/lib/netstandard1.6/Fable.Core.dll
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Result.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Promise.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Json.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/PromiseSeq/Type.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/PromiseSeq/Module.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/PromiseSeq/Extensions.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Fetch.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/IndexedDB.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Date/Local.fs
   /home/z/.nuget/packages/fable.powerpack/1.3.0/fable/src/Date/Format.fs
   /home/z/.nuget/packages/fable.elmish/1.0.0/fable/cmd.fs
   /home/z/.nuget/packages/fable.elmish/1.0.0/fable/program.fs
   /home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/prelude.fs
   /home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs
   /home/z/.nuget/packages/fable.elmish.browser/1.0.0/fable/navigation.fs
   /home/z/.nuget/packages/fable.elmish.debugger/1.0.0/fable/Fable.Import.RemoteDev.fs
   /home/z/.nuget/packages/fable.elmish.debugger/1.0.0/fable/debugger.fs
   /home/z/.nuget/packages/fable.elmish.hmr/1.0.0/fable/hmr.fs
   /home/z/.nuget/packages/fable.react/1.2.1/fable/Fable.Import.React.fs
   /home/z/.nuget/packages/fable.react/1.2.1/fable/Fable.Helpers.React.fs
   /home/z/.nuget/packages/fable.elmish.react/1.0.0/fable/common.fs
   /home/z/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs
   /home/z/.nuget/packages/fable.elmish.react/1.0.0/fable/react-native.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/ReleaseNotes.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Server/Shared/Domain.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/Messages.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/Style.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/Utils.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/pages/Menu.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/pages/WishList.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/pages/Login.fs
   /home/z/Projects/Strawberry/strawberry-backend/src/Client/App.fs
Parsing ./Client.fsproj...
fable: Compiled Client.fsproj
```
You can see the `-r`  parameters' path doesn't match the paths in errors, because my home directory is a symbol link, usually it should be a mount point, but I mounted the disk partition in another directory, and symbol linked a subfolder to the home directory, it's not the first time cause problems, I can't believe I thought it would be a good idea :man_facepalming: .  Mounting the home normally solved my error.

**Comment by MangelMaxime** [comment]
So this is probably related to webpack.  When i was using it with symlink I needed to set a specific setting something like `followSymlink:  false ` if I remember well

**Comment by zaaack** [comment]
@MangelMaxime Not  exactly, the error comes from [dotnet-fable](https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/StateUtil.fs),  I'm pretty sure this line is relative: https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/StateUtil.fs#L132 the path from msg is resolved, but not the project. Maybe I can create a pr later.
