### ISSUE TITLE
Compiler errors in VS Code but site still works

### ISSUE THREAD

**Issue by misterspeedy** [SAFE-Stack/SAFE-BookStore#244]
### Description

Compiler errors in VS code but site still works and editor changes are reflected.

### Repro steps

1. Install prerequisites.

2. Clone repo

3. Run ``build.cmd``

4. Open folder in VS Code.

5. Perform a harmless edit or two in ``home.fs`` (eg. phrasing of prompts) and save.

6. Observe that edits are reflected in browser.

### Expected behavior

Valid edits should not trigger compiler errors.

### Actual behavior

Red squigglies appear over Fable-related items in editor and compiler errors appear in VS Code ``Problems`` tab.   First error is "the namespace or module Fable is not defined".

### Known workarounds

None.

### Related information 

* Operating system: Windows 10 Build 1703 64bit
* Branch: master
* VS Code version: 1.18.1 (Shell 1.7.9, Node 7.9.0, architecture ia32)
* Ionide version: Ionide-fsharp: 3.13.0 Ionide FAKE: 1.2.3 Ionide-Paket: 1.8.1

**Comment by misterspeedy** [comment]
@enricosada

**Comment by misterspeedy** [comment]
Updated to Ionide 3.13.2, still happens.

**Comment by misterspeedy** [comment]
Started performing the Ionide install steps in case something is missing from the SAFE build or installation steps.  Did this:

`choco install windows-sdk-8.0 -y`
`choco install visualfsharptools -y`

On `build.cmd` got this:

  1) System.Exception: dotnet build failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args)
   at FSI_0005.Build.clo@134-5.Invoke(Unit _arg3)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

**Comment by misterspeedy** [comment]
Some files seem to have been changed locally:

        modified:   .paket/Paket.Restore.targets
        modified:   src/Client/ReleaseNotes.fs
        modified:   src/Client/pages/Home.fs

So did a `git checkout .`.  Same build error as previous comment.

**Comment by misterspeedy** [comment]
Continued Ionide install steps:

`choco install microsoft-build-tools -y` <-- already installed.
`choco install visualstudiocode -y`

Got dialog "Please uninstall the 32 bit version of Code before installing this 64 bit version.  
Uninstalled Code from Windows "Apps and Features".
Repeated

`choco install visualstudiocode -y`

Ran Code.  Verified that Ionide is still installed.

Made another harmless edit to SAFE-Bookstore code (added a space to a prompt).  Same issue - red squigglies starting at the first `open Fable...`.

**Comment by misterspeedy** [comment]
Restarted bash, ran `build.cmd`, same error as was introduced after installing `visualfsharptools`:

---------------------------------------------------------------------
  1) System.Exception: dotnet build failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args)
   at FSI_0005.Build.clo@134-5.Invoke(Unit _arg3)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

**Comment by misterspeedy** [comment]
Cloned another copy of the bookstore source elsewhere.
Ran a `./build.cmd`, this succeeded.
Re-ran Code and opened the folder in the new clone.
Added one space to a prompt as before - again red squigglies as before.

**Comment by misterspeedy** [comment]
Repeated the steps suggested by @enricosada:

`F#: Clear Cache' <-- succeeded
`dot net restore BookStore.sln` <-- some packages incompatible - see output below
`Reload Window`

Again red squigglies as soon as I made an edit.




  Restoring packages for C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj...
  Restoring packages for C:\code\temp\SAFE-BookStore\test\UITests\UITests.fsproj...
  Restoring packages for C:\code\temp\SAFE-BookStore\src\Client\Client.fsproj...
  Restoring packages for C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.DotNet.Watcher.Tools 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Watcher.Tools 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [C:\code\temp\SAFE-BookStore\BookStore.sln]
  Restore failed in 473.86 ms for C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj.
  Restoring packages for C:\code\temp\SAFE-BookStore\src\Client\Client.fsproj...
  Generating MSBuild file C:\code\temp\SAFE-BookStore\test\UITests\obj\UITests.fsproj.nuget.g.props.
  Writing lock file to disk. Path: C:\code\temp\SAFE-BookStore\test\UITests\obj\project.assets.json
  Restore completed in 485.04 ms for C:\code\temp\SAFE-BookStore\test\UITests\UITests.fsproj.
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package dotnet-fable 1.3.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package dotnet-fable 1.3.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [C:\code\temp\SAFE-BookStore\BookStore.sln]
  Restore failed in 14.5 ms for C:\code\temp\SAFE-BookStore\src\Client\Client.fsproj.
  Generating MSBuild file C:\code\temp\SAFE-BookStore\src\Client\obj\Client.fsproj.nuget.g.props.
  Generating MSBuild file C:\code\temp\SAFE-BookStore\src\Client\obj\Client.fsproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\code\temp\SAFE-BookStore\src\Client\obj\project.assets.json
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.FileSystemGlobbing 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileSystemGlobbing 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Primitives 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Primitives 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Configuration.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Configuration 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.FileProviders.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileProviders.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.FileProviders.Physical 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileProviders.Physical 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Configuration.FileExtensions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.FileExtensions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Logging 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Logging.Console 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Console 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Azure.WebJobs.Core 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs.Core 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Extensions.Configuration.Json 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.Json 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Azure.WebJobs 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Azure.WebJobs.Extensions 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs.Extensions 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0) [C:\code\temp\SAFE-BookStore\BookStore.sln]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v2.0. [C:\code\temp\SAFE-BookStore\BookStore.sln]
  Restore completed in 705.69 ms for C:\code\temp\SAFE-BookStore\src\Client\Client.fsproj.
  Generating MSBuild file C:\code\temp\SAFE-BookStore\src\Server\obj\Server.fsproj.nuget.g.props.
  Generating MSBuild file C:\code\temp\SAFE-BookStore\src\Server\obj\Server.fsproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\code\temp\SAFE-BookStore\src\Server\obj\project.assets.json
  Restore failed in 866.31 ms for C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj.

  Errors in C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj
      Package Microsoft.DotNet.Watcher.Tools 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Watcher.Tools 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
      One or more packages are incompatible with .NETCoreApp,Version=v1.0.

  Errors in C:\code\temp\SAFE-BookStore\src\Client\Client.fsproj
      Package dotnet-fable 1.3.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package dotnet-fable 1.3.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
      One or more packages are incompatible with .NETCoreApp,Version=v1.0.

  Errors in C:\code\temp\SAFE-BookStore\src\Server\Server.fsproj
      Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.FileSystemGlobbing 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileSystemGlobbing 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Primitives 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Primitives 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Configuration.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Configuration 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.EnvironmentVariables 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.FileProviders.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileProviders.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.FileProviders.Physical 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.FileProviders.Physical 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Configuration.FileExtensions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.FileExtensions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Options 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Options 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Logging 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Logging.Console 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Logging.Console 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Azure.WebJobs.Core 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs.Core 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.Configuration.Json 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.Configuration.Json 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Azure.WebJobs 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Azure.WebJobs.Extensions 3.0.0-beta3 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Azure.WebJobs.Extensions 3.0.0-beta3 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      One or more packages are incompatible with .NETCoreApp,Version=v2.0.

  NuGet Config files used:
      C:\code\temp\SAFE-BookStore\NuGet.Config
      C:\Users\kitea\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json

**Comment by misterspeedy** [comment]
Noticed this line from the previous step:

> Package dotnet-fable 1.3.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package dotnet-fable 1.3.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

Maybe I don't have .NET Core 2?

Installing...

**Comment by forki** [comment]
We are on dotnet sdk 2.0.3 - please install it. I think it's listed in
readme

Am 25.11.2017 10:56 schrieb "Kit Eason" <notifications@github.com>:

**Comment by misterspeedy** [comment]
Installed .NET Core SDK 2.0.3 (x64).
Reran `build.cmd` <-- succeeded 
Ran `build.cmd run`
Book store came up in browser ok.
No red squigglies and editor changes are reflected in browser on save.

**Comment by misterspeedy** [comment]
OK, everything works now and Code/Ionide looks extremely nice.

I'm new to all this VSCode and Core stuff, but my guess is that a dependency on Core 2.0.3 has crept in somewhere but isn't reflected everywhere else.  For example the SAFE doc states:

> dotnet SDK 2.0.2 is required but it will be downloaded automatically by the build script if not installed (see below).

...but things only started working when I explicitly downloaded and installed .NET Core SDK 2.0.3.  I don't known whether any doc or build changes might be required to give first time users a better experience?

**Comment by forki** [comment]
Please send a fix. We are on 2.0.3

Am 25.11.2017 11:27 schrieb "Kit Eason" <notifications@github.com>:

**Comment by misterspeedy** [comment]
@forki A fix to.... ?

**Comment by forki** [comment]
To where you read 2.0.2

Am 25.11.2017 13:18 schrieb "Kit Eason" <notifications@github.com>:

**Comment by misterspeedy** [comment]
Isn't it more than that though, as it also states that the dependency will be downloaded automatically, which it wasn't - so presumably a build or config change somewhere in the SAFE-Bookstore code too?  (I'm happy to do this but want to make sure we're all on the same page.)

**Comment by forki** [comment]
Oh it was. Build worked right? It's just that ionide needs it's own copy

Am 25.11.2017 14:07 schrieb "Kit Eason" <notifications@github.com>:

Isn't it more than that though, as it also states that the dependency will
be downloaded automatically, which it wasn't - so presumably a build or
config change somewhere in the SAFE-Bookstore code too? (I'm happy to do
this but want to make sure we're all on the same page.)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SAFE-Stack/SAFE-BookStore/issues/244#issuecomment-346939563>,
or mute the thread

**Comment by forki** [comment]
But yes we should remove that sentence and just tell people to install it

Am 25.11.2017 14:11 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by misterspeedy** [comment]
@isaacabraham Shall I go ahead and do this (i.e. update doc as Steffen suggests)?

**Comment by isaacabraham** [comment]
I'm happy for the update to the docs - please submit a PR, if there's anything more that's needed we'll say :-) Thanks!

**Comment by misterspeedy** [comment]
PR'd.
