### ISSUE TITLE
client tests fail on running build.cmd

### ISSUE THREAD

**Issue by ghost** [SAFE-Stack/SAFE-BookStore#272]
### Description

When I run `build.cmd` without any parameters, the build fails on the `RunClientTests` target. Everything works fine with `build.cmd run` though.
 
### Steps to reproduce
Try to run from a local repository that does not have any remote (i.e. when starting an own project from zipped template)

### Actual behavior
```
Hosting environment: Production
Content root path: C:\Users\K\Desktop\iacm-page\src\Client
Now listening on: http://0.0.0.0:8085
Application started. Press Ctrl+C to shut down.
[INFO  - 2018-01-23T10:58:08.782Z] GhostDriver - Main - running on port 50384
[INFO  - 2018-01-23T10:58:08.942Z] Session [4c0e3280-002c-11e8-9301-195ee80cbf81] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanEXPECTO version

[11:58:09 INF] EXPECTO? Running tests... <Expecto>
[11:58:24 ERR] client tests/login with test user errored in 00:00:13.1190000 <Expecto>
OpenQA.Selenium.WebDriverTimeoutException: Timed out!
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f)
   at canopy.core.click[a](a item)
   at UITests.Tests.login() in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 25
   at UITests.Tests.tests@41-1.Invoke(Unit unitVar0) in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 43
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
[11:58:38 ERR] client tests/validate form fields errored in 00:00:14.3820000 <Expecto>
OpenQA.Selenium.WebDriverTimeoutException: Timed out!
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f)
   at canopy.core.click[a](a item)
   at UITests.Tests.login() in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 25
   at UITests.Tests.tests@46-2.Invoke(Unit unitVar0) in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 48
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
[11:58:53 ERR] client tests/create and remove book errored in 00:00:14.4520000 <Expecto>
OpenQA.Selenium.WebDriverTimeoutException: Timed out!
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f)
   at canopy.core.click[a](a item)
   at UITests.Tests.login() in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 25
   at UITests.Tests.tests@70-3.Invoke(Unit unitVar0) in C:\Users\K\Desktop\iacm-page\test\UITests\Tests.fs:line 72
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
[11:58:53 INF] EXPECTO! 4 tests run in 00:00:44.0357989 - 1 passed, 0 ignored, 0 failed, 3 errored.  <Expecto>
Running build failed.
Error:
Expecto test of assembly 'C:\Users\K\Desktop\iacm-page\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code 2.
Starting FinalTarget: KillProcess
Searching for processes with name = dotnet
Trying to kill process dotnet (Id = 10056)
Trying to kill process dotnet (Id = 15112)
Searching for processes with name = dotnet.exe

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0686498
InstallDotNetCore   00:00:00.1307148
InstallClient       00:00:01.6704640
SetReleaseNotes     00:00:00.0037617
BuildServer         00:00:02.5438471
BuildClient         00:00:23.6100938
BuildServerTests    00:00:03.8778374
RunServerTests      00:00:04.4914670
BuildClientTests    00:00:01.2986721
RenameDrivers       00:00:00.0004665
KillProcess         00:00:00.0199834
RunClientTests      Failure
Total:              00:01:43.7475760
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Fake.UnitTestCommon+FailedTestsException: Expecto test of assembly 'C:\Users\K\Desktop\iacm-page\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code 2.
   at Fake.Testing.Expecto.Expecto(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\Expecto\Expecto.fs:line 126
   at FSI_0005.Build.clo@163-12.Invoke(Unit _arg10)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

### Related information 

* Windows 10 Education Version 10.0.16299 Build 16299
* started my project from commit 943d9c3fc40128474e5d9c100dc5094aaff39a28
*  `dotnet --version` = 2.1.3

**Comment by kfrie** [comment]
### Update 

Everything worked fine after I set up a remote repository on GitHub for my prototype (worked only with local git repository to this point) and my local branches were tracking remote ones.
