### ISSUE TITLE
Build fails on SDK 2.1.300-preview1-008009 at BuildServer step

### ISSUE THREAD

**Issue by cartermp** [SAFE-Stack/SAFE-BookStore#283]
SDK link [here](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180126-01/final/assets/Sdk/2.1.300-preview1-008009/dotnet-sdk-2.1.300-preview1-008009-win-x64.exe).

Info:
```
Windows 10
VS:D15.6/27326.01(15.6 Preview 4) - internal VS build
Node.js: V8.9.4 LTS
Yarn --version: 1.3.2
Paket version: 5.132.4
CLI/SDK: 2.1.300-preview1-008009
```

Failure from running `build.cmd`:
```
System.Exception: dotnet build failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in C:\Users\vseqa1\Documents\test\SAFE-BookStore-master\build.fsx:line 64
   at FSI_0005.Build.clo@119-5.Invoke(Unit _arg3) in C:\Users\vseqa1\Documents\test\SAFE-BookStore-master\build.fsx:line 120
  at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by cartermp** [comment]
Note: leaving this here for now so that it's tracked, since we did pick this up when building against this project. We'll route this elsewhere if it turns out not to be an issue with the SAFE project

**Comment by cartermp** [comment]
Log here: 
[FullLog.txt](https://github.com/SAFE-Stack/SAFE-BookStore/files/1676123/FullLog.txt)

Relevant:

```
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(13,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(13,41): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(14,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(14,42): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(15,59): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(16,58): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(17,54): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Auth.fs(21,83): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(34,17): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(39,27): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(39,27): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(40,36): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(40,36): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(41,33): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(41,33): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(31,5): error FS0043: A unique overload for method 'GetAwaiter' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter<'a> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(77,14): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(77,5): error FS0041: A unique overload for method 'Bind' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : configurableTaskLike: ^a0 * continuation:( ^a3 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member ConfigureAwait :  ^a0 * bool ->  ^a1) and  ^a1 : (member GetAwaiter :  ^a1 ->  ^a2) and  ^a2 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a2 : (member get_IsCompleted :  ^a2 -> bool) and  ^a2 : (member GetResult :  ^a2 ->  ^a3), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : task:Task<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b>, member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : taskLike: ^a0 * continuation:( ^a2 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member GetAwaiter :  ^a0 ->  ^a1) and  ^a1 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a1 : (member get_IsCompleted :  ^a1 -> bool) and  ^a1 : (member GetResult :  ^a1 ->  ^a2), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : work:Async<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(52,5): error FS0043: A unique overload for method 'GetAwaiter' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter<'a> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(91,17): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(95,9): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(96,12): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(96,86): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(95,5): error FS0041: A unique overload for method 'Bind' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : configurableTaskLike: ^a0 * continuation:( ^a3 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member ConfigureAwait :  ^a0 * bool ->  ^a1) and  ^a1 : (member GetAwaiter :  ^a1 ->  ^a2) and  ^a2 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a2 : (member get_IsCompleted :  ^a2 -> bool) and  ^a2 : (member GetResult :  ^a2 ->  ^a3), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : task:Task<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b>, member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : taskLike: ^a0 * continuation:( ^a2 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member GetAwaiter :  ^a0 ->  ^a1) and  ^a1 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a1 : (member get_IsCompleted :  ^a1 -> bool) and  ^a1 : (member GetResult :  ^a1 ->  ^a2), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : work:Async<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(102,14): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(105,9): error FS0043: A unique overload for method 'GetAwaiter' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter<'a> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(104,5): error FS0043: A unique overload for method 'GetAwaiter' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter<'a> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Storage\AzureTable.fs(102,5): error FS0041: A unique overload for method 'Bind' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : configurableTaskLike: ^a0 * continuation:( ^a3 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member ConfigureAwait :  ^a0 * bool ->  ^a1) and  ^a1 : (member GetAwaiter :  ^a1 ->  ^a2) and  ^a2 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a2 : (member get_IsCompleted :  ^a2 -> bool) and  ^a2 : (member GetResult :  ^a2 ->  ^a3), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : task:Task<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b>, member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : taskLike: ^a0 * continuation:( ^a2 -> Giraffe.TaskBuilder.Step<'a>) -> Giraffe.TaskBuilder.Step<'a> when  ^a0 : (member GetAwaiter :  ^a0 ->  ^a1) and  ^a1 :> Runtime.CompilerServices.ICriticalNotifyCompletion and  ^a1 : (member get_IsCompleted :  ^a1 -> bool) and  ^a1 : (member GetResult :  ^a1 ->  ^a2), member Giraffe.TaskBuilder.ContextInsensitiveTaskBuilder.Bind : work:Async<'a> * continuation:('a -> Giraffe.TaskBuilder.Step<'b>) -> Giraffe.TaskBuilder.Step<'b> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Database.fs(29,17): error FS0043: A unique overload for method 'GetAwaiter' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Task.GetAwaiter() : System.Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : System.Runtime.CompilerServices.TaskAwaiter<'a> [C:\Users\vseqa1\Documents\SAFE-BookStore-master\src\Server\Server.fsproj]
    0 Warning(s)
    29 Error(s)

Time Elapsed 00:00:22.77
Running build failed.
```

**Comment by forki** [comment]
ok this looks rather serious. I can repro and I wonder if you ship a different version of the compiler?

I looked at the very first error in Auth.fs(13,13) - the new version has issues with the type inference. Adding an explicit type hint in line 10 makes the error go away:

    let! (login:Domain.Login) = FableJson.getJsonFromCtx<Domain.Login> ctx

/cc @kevinransom @dsyme @TIHan @brettfo

**Comment by forki** [comment]
Ok looked a bit into the following errors. It seems to always be the case that `let!` type inference is broken

**Comment by gerardtoconnor** [comment]
Sorry been really busy in work.

```
A type annotation may be needed. Candidates: Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter, Task.GetAwaiter() : Runtime.CompilerServices.TaskAwaiter<'a> 
```

Will have look this evening, this is bizarre its detecting this "overload", its like 2 CS targets loaded or something

**Comment by forki** [comment]
It would be interesting to know if it repros if we copy the tasks file here or if it is only because of the packagereference

**Comment by forki** [comment]
repros on CI: https://github.com/SAFE-Stack/SAFE-BookStore/pull/284

**Comment by forki** [comment]
Just tested: it's unrelated to package references - if I put Task.fs as a file into the project an remove the package reference it's still failing

**Comment by gerardtoconnor** [comment]
@forki 
It appears that compiler is loading in `Runtime.CompilerServices.TaskAwaiter` as well as  `Runtime.CompilerServices.TaskAwaiter<'a>` for generic GetAwaiter() such that is unable to resolve which method to bind to. our SRTP:
```

        static member inline GenericAwait< ^abl, ^awt, ^inp
                                            when ^abl : (member GetAwaiter : unit -> ^awt)
                                            and ^awt :> ICriticalNotifyCompletion
                                            and ^awt : (member get_IsCompleted : unit -> bool)
                                            and ^awt : (member GetResult : unit -> ^inp) >
            (abl : ^abl, continuation : ^inp -> 'out Step) : 'out Step =
                let awt = (^abl : (member GetAwaiter : unit -> ^awt)(abl)) // get an awaiter from the awaitable
                if (^awt : (member get_IsCompleted : unit -> bool)(awt)) then // shortcut to continue immediately
                    continuation (^awt : (member GetResult : unit -> ^inp)(awt))
                else
                    Await (awt, fun () -> continuation (^awt : (member GetResult : unit -> ^inp)(awt)))
```
does not allow constraint stipulation on generic type parameter (that I am aware of?) so not sure how this can be resolved, we either have to

1. Modify SRTP with additional bind for 2 cases of GetAwaiter (base & generic), which I don't think is currently possible with SRTP?
2. Add overload based on GetResult given base TaskAwaiter is unit/void in and out while genric returns the expeceted 'out type

I have uploaded a test version that uses getResult 'Unit-Overload` approach here https://github.com/giraffe-fsharp/Giraffe.Tasks/tree/unit-overload, if you can test with this implementation, and see if the `GetAwaiter` is not able to resolve?

**Comment by cartermp** [comment]
ping @dsyme again - we currently need to skip SAFE validation internally so as not to block on any further updates to the CLI. We will want to identify if this is a compiler bug for the latest F# compiler or not.

**Comment by dsyme** [comment]
@cartermp Sorry, I don't always see ping's if I'm subscribed to the repo and auto-filing notifications away

Could someone open a bug on visualfsharp if there is a compiler bug please?  It looks like https://github.com/SAFE-Stack/SAFE-BookStore/pull/284 repros it?

Thanks

**Comment by forki** [comment]
@dsyme I tried to repro directly in visualfsharp. But failed. See https://github.com/Microsoft/visualfsharp/pull/4285

**Comment by forki** [comment]
The same issue persists after upgrade to giraffe 1.0 which uses the TaskBuilder.fs instead of giraffe.tasks - see #293. I think it's rather serious since it would break all safe stack apps.

**Comment by forki** [comment]
As requested by @dsyme: https://github.com/Microsoft/visualfsharp/issues/4343

**Comment by cartermp** [comment]
Closing this, as the issue is squarely in the F# compiler
