### ISSUE TITLE
UI Test failure on .NET Core build verification

### ISSUE THREAD

**Issue by cartermp** [SAFE-Stack/SAFE-BookStore#311]
**Edit:**

Full log here: https://github.com/SAFE-Stack/SAFE-BookStore/issues/311#issuecomment-371190446

**Environmental info**

VS: D15.7stg/27505.3002 (15.7 Preview 1)
Node.js: V8.9.4 LTS
Yarn --version:1.5.1
Paket version: 5.148.0
VS .NET Core SDK - 2.1.100: 2.1.100 ( runtime - 2.0.5)

**Repro steps**

Install the needed deps for SAFE-Bookstore and run `build.cmd`. Error produced:

```
1) Fake.UnitTestCommon+FailedTestsException: Expecto test of assembly 'C:\Users\CORBVT\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\SAFE-BookStore-master\SAFE-BookStore-master\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code 2.
   at Fake.Testing.Expecto.Expecto(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\Expecto\Expecto.fs:line 126
   at FSI_0005.Build.clo@163-12.Invoke(Unit _arg10)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by cartermp** [comment]
Note: the VS version is likely not needed; it's just there since that's what was installed.

I'm not sure how the UI tests here work with Canopy, but I suspect that this isn't related to the version of the .NET Core SDK that's under test.

**Comment by forki** [comment]
can you please give full error? this not showing the actual expectot output

**Comment by psfinaki** [comment]
I confirm that, got this thing when running release script. Full error:
```
[17:00:16 ERR] client tests/create and remove book errored in 00:02:40.0230000 <Expecto>
OpenQA.Selenium.WebDriverTimeoutException: Timed out!
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f)
   at canopy.core.op_ComposeLeft[a](a item, String text)
   at UITests.Tests.tests@70-3.Invoke(Unit unitVar0) in C:\Users\pese\Desktop\SAFE-BookStore\test\UITests\Tests.fs:line 85
   at Expecto.Impl.execTestAsync@874-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
[17:00:16 INF] EXPECTO! 4 tests run in 00:05:08.4797301 - 3 passed, 0 ignored, 0 failed, 1 errored.  <Expecto>
[ERROR - 2018-03-07T16:00:17.740Z] RouterReqHand - _handle.error - {"stack":"_translateKey@phantomjs://code/inputs.js:268:55\n_sendKeys@phantomjs://code/inputs.js:217:42\n_postValueCommand@phantomjs://code/webelement_request_handler.js:288:41\n_handle@phantomjs://code/we
belement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:120:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46","line":268,"so
urceURL":"phantomjs://code/inputs.js"}

  phantomjs://platform/console++.js:263 in error
[INFO  - 2018-03-07T16:00:17.794Z] ShutdownReqHand - _handle - About to shutdown
Running build failed.
Error:
Expecto test of assembly 'C:\Users\pese\Desktop\SAFE-BookStore\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code 2.
Starting FinalTarget: KillProcess
Searching for processes with name = dotnet
Trying to kill process dotnet (Id = 13372)
Trying to kill process dotnet (Id = 5880)
Searching for processes with name = dotnet.exe

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0965289
InstallDotNetCore   00:00:00.2429785
InstallClient       00:00:03.2913431
SetReleaseNotes     00:00:00.0049714
BuildServer         00:00:04.3700232
BuildClient         00:00:28.4515895
BuildServerTests    00:00:06.4289201
RunServerTests      00:00:09.4134053
BuildClientTests    00:00:03.0007435
RenameDrivers       00:00:00.0009485
KillProcess         00:00:00.0317423
RunClientTests      Failure
Total:              00:06:35.0042812
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Fake.UnitTestCommon+FailedTestsException: Expecto test of assembly 'C:\Users\pese\Desktop\SAFE-BookStore\test\UITests\bin\Debug\net461\UITests.exe' failed. Process finished with exit code 2.
   at Fake.Testing.Expecto.Expecto(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\Expecto\Expecto.fs:line 126
   at FSI_0005.Build.clo@163-12.Invoke(Unit _arg10)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

**Comment by psfinaki** [comment]
Workaround for release: comment/remove   `==> "RunClientTests"` and `==> "TestDockerImage"` in the build script with all the consequences.

**Comment by cartermp** [comment]
Thanks for the repro @psfinaki - I've been running around over the past day and haven't had the time to get the full error.

**Comment by forki** [comment]
@psfinaki is it that canopy can't find the remove button?

@cartermp are you sure it's the same thing?

**Comment by psfinaki** [comment]
@forki, I do not know actually, it might take quite some time for me to understand.. I have not worked with canopy before and also still have a vague idea how things work and get tested here.

**Comment by forki** [comment]
No problem. I was seeing that "remove" error today on one of my machines. So I was wondering if it's the same. But it does not happen on CI.

**Comment by cartermp** [comment]
I suspect it may be the same; I can try it again sometime later this week but between MVP summit and dealing with our apartment getting sold I'm short for time this week 😢

**Comment by forki** [comment]
don't worry. let's assume it's the same and fix. after a while you can check if you still see the error ;-)

**Comment by cartermp** [comment]
Sounds like a good plan!

**Comment by YunWeiaa** [comment]
Repro on D16.0/28322.00 (16.0 preview 1.0)

**Comment by yunwei00q** [comment]
Repro on D16.4/[29512.137](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/a291dd212be7e68732077d105224d0095f70a42f/e1d00ea3-764c-6311-1c21-4d6d20e48e60%3bchannels/internal/Preview/bootstrappers/fixed/Enterprise/vs_Enterprise.exe)(16.4.0 Preview 5.0)

**Comment by JiahongJin1** [comment]
error message on SDK 6.0.102

Running build failed.
Error:
System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00088] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00008] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(string,string)
  at Fake.DotNetCli.downloadSDK@521 (System.String tempDir, System.String downloadPath, System.String archiveFileName) [0x0005b] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 
  at Fake.DotNetCli.InstallDotNetSDK (System.String sdkVersion) [0x00230] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 
  at FSI_0005.Build+clo@103-5.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x00006] in <fc1d66fe7e414b7ca16d2d6905c93570>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0198982
InstallDotNetCore   Failure
Total:              00:21:52.3333578
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00088] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00008] in <2cef2219e8e14eb5a8eef57e30f81ac0>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(string,string)
  at Fake.DotNetCli.downloadSDK@521 (System.String tempDir, System.String downloadPath, System.String archiveFileName) [0x0005b] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 
  at Fake.DotNetCli.InstallDotNetSDK (System.String sdkVersion) [0x00230] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 
  at FSI_0005.Build+clo@103-5.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x00006] in <fc1d66fe7e414b7ca16d2d6905c93570>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5c90a2e0ccf1c534a7450383e0a2905c>:0 
---------------------------------------------------------------------

**Comment by JiahongJin1** [comment]
error message on SDK 6.102:
[Logs.txt](https://github.com/SAFE-Stack/SAFE-BookStore/files/7938710/Logs.txt)
